//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioButton_Insert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhobby
    {
        public int hid { get; set; }
        public string hname { get; set; }
        public bool IsChecked { get; set; }
        
    }

   public class HobbyModel
    {
        public List<tblhobby> getHobby { get; set; }
    }

}
